### ISSUE TITLE
Screenshots need update

### ISSUE THREAD

**Issue by amcolash** [thumbsup/theme-flow#2]
The screenshots need an update. I love the simple mac-esque style of the screenshots. Did you use a special program for that? I am happy to do the screenshots if you'd like.

**Comment by rprieto** [comment]
I made a little script that I run locally:
- generate the gallery with sample photos
- take a screenshot with https://www.npmjs.com/package/pageres
- add a macOS-style border and save the final image 

I'll push that code to a new repo in thumbsup if you want to use it.

**Comment by rprieto** [comment]
Another cheaper option though is to take a regular screenshot and paste it over the existing macOS frame 🙂

**Comment by amcolash** [comment]
Of course I could manually do it 😉 

I was just asking to see if you had a more automated flow. Yeah posting that script sounds like a good plan - just to make things consistent across the themes.

**Comment by amcolash** [comment]
Gave a quick shot at them with ae2aa0913. Have a feeling you have some magic of scaling things down a bit too with your script.

**Comment by rprieto** [comment]
Brilliant, thank you! I had actually abandonned that script, I should look it up again and add it to Github.

**Comment by amcolash** [comment]
Realized there were screenshots so closed this out. Someone made a PR which made me do some housekeeping around here.
