### ISSUE TITLE
Publish to npm repo

### ISSUE THREAD

**Issue by amcolash** [thumbsup/theme-flow#3]
It doesn't look like the theme has yet been pushed to npm. Once added, it will be much easier to use this theme!

**Comment by rprieto** [comment]
Thanks. I just setup automatic publishing for every tagged commit on `master`. To publish a version, simply run:

```bash
git checkout master
npm version major|minor|patch
git push && git push --tags
```

**Comment by amcolash** [comment]
I tagged a version a few days back, but it doesn't appear to be in npm. Is there a 1 time setup to make a new package? Seems like travis kicked off a build just fine though :thinking:

**Comment by amcolash** [comment]
Looks like it popped up the other day on npm. Yay! I think this one is set to add to the official repo (if you think it is set).
